# Generated by Django 4.0.4 on 2022-08-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('approved', 'approved'), ('going', 'going'), ('finished', 'finished'), ('canceled', 'canceled')], default='sent', max_length=25),
        ),
    ]
