# Generated by Django 4.0.4 on 2022-08-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_proposal_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
