# Generated by Django 4.0.4 on 2022-08-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_portfolio_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('canceled', 'canceled')], default='pending', max_length=20),
        ),
    ]
