# Generated by Django 4.0.4 on 2022-08-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_portfolio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
