# Generated by Django 4.0.4 on 2022-08-15 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_category_image_category_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=300)),
                ('extra_skills', models.CharField(max_length=300, null=True)),
                ('is_hourly', models.BooleanField()),
                ('hourly_from_budget', models.BigIntegerField(null=True)),
                ('hourly_to_budget', models.BigIntegerField(null=True)),
                ('maximum_project_budget', models.BigIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='posts/')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('skills', models.ManyToManyField(blank=True, to='registration.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
