# Generated by Django 4.0.4 on 2022-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
