# Generated by Django 4.0.4 on 2022-08-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_file_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
