# Generated by Django 4.0.4 on 2022-08-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_address_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('approved', 'approved'), ('going', 'going'), ('finished', 'finished'), ('archived', 'archived')], default='sent', max_length=20),
        ),
    ]
