# Generated by Django 4.0.4 on 2022-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
