# Generated by Django 4.0.4 on 2022-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('approved', 'approved'), ('going', 'going'), ('finished', 'finished'), ('archived', 'archived'), ('canceled', 'canceled')], default='sent', max_length=20),
        ),
    ]
