# Generated by Django 4.0.4 on 2022-08-26 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
