# Generated by Django 4.0.4 on 2022-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
