# Generated by Django 4.0.4 on 2022-08-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
