# Generated by Django 4.0.4 on 2022-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='projects',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='experience',
            new_name='payment_hourly',
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
