# Generated by Django 4.0.4 on 2022-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_earnings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.BigIntegerField(default=0),
        ),
    ]
