# Generated by Django 4.0.4 on 2022-08-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_total_earnings_user_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
