# Generated by Django 4.0.4 on 2022-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_category_image'),
        ('user', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, to='registration.category'),
        ),
    ]
