# Generated by Django 4.0.4 on 2022-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
