# Generated by Django 4.0.4 on 2022-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='status',
        ),
        migrations.AddField(
            model_name='proposal',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('archived', 'archived')], default='pending', max_length=25),
        ),
    ]
