# Generated by Django 4.0.4 on 2022-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_review_rate_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
