# Generated by Django 4.0.4 on 2022-08-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_review_is_for_post_alter_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_for_post',
            new_name='is_client',
        ),
    ]
