# Generated by Django 4.0.4 on 2022-08-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='card',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
