# Generated by Django 4.0.4 on 2022-08-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_invoice_date_alter_invoice_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
