# Generated by Django 4.0.4 on 2022-08-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_alter_portfolio_date'),
        ('proposals', '0011_statuschanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschanges',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.portfolio'),
        ),
    ]
